### ISSUE TITLE
Invalid Atom feed

### ISSUE THREAD

**Issue by FraGag** [cmr/this-week-in-rust#268]
Since yesterday (August 2nd), somewhere between 15:09:58 and 16:10:56 EDT (according to my computer's clock!), [the Atom feed for This Week in Rust](https://this-week-in-rust.org/atom.xml) is invalid. Specifically, [feeds-to-pocket](https://github.com/FraGag/feeds-to-pocket) panics<sup>1</sup> when processing the feed because the `<entry>` elements are missing the `<updated>` subelement, which is [required](https://tools.ietf.org/html/rfc4287#section-4.1.2) by the Atom spec.

----

<sup>1</sup> It panics because one of my dependencies uses `unwrap()` instead of bubbling up an `Err`, so I'll take this opportunity to fix it! I downloaded the invalid feed and I'll do my tests with this copy.

**Comment by nasa42** [comment]
I can assert that this issue is likely because of my recent upgrade from Ubuntu 14.04 to 16.04, as I ended up reinstalling all of my Python3 packages used by TWiR. It is likely that there is a version mismatch in some packages from my previous setup which is causing this issue.
I'll dig in my backups made before upgrade, compare, and fix this.

**Comment by nasa42** [comment]
This was a result of upgrading from `feedgenerator` 1.7 to 1.8. (More information here: https://github.com/getpelican/pelican/issues/1933).

For now, I'm locking `feedgenerator` to 1.7.
