### ISSUE TITLE
TWiR links are too light now 

### ISSUE THREAD

**Issue by pravic** [cmr/this-week-in-rust#767]
Which makes them almost unreadable.

Vivaldi, macOS:

![image](https://user-images.githubusercontent.com/724639/49640563-fcad9f80-fa1e-11e8-9956-3ab2d6cf28ab.png)

Though Safari shows different colors:

![image](https://user-images.githubusercontent.com/724639/49640780-7a71ab00-fa1f-11e8-9d1b-1fe1e3582c08.png)

**Comment by nasa42** [comment]
One more user report here: https://twitter.com/MikhailT/status/1105893346759708672

**Comment by nasa42** [comment]
Could you please confirm what is the colour of text? It should be `#444444` (`rgb(68, 68, 68)`).

**Comment by pravic** [comment]
It is `#444`. Why?

**Comment by nasa42** [comment]
Because the same colour `#444444` is shown differently in two browsers (as shown in screenshots above), I'd suspect this is an issue with the font that the browser is picking.

I'm not sure if this can be fixed from TWiR's side. We use the font-family `"Helvetica Neue", Helvetica, Arial, sans-serif`, and because another browser (Safari) is picking up the correct font, I'd suspect it as an issue within the other browser (Vivaldi).

**Comment by pravic** [comment]
I see. I will compare the selected fonts on different browsers.

**Comment by nasa42** [comment]
I'll close this issue for now. Please feel free to reopen when more information is available.
